name: CI

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup actionLint
        uses: KeisukeYamashita/setup-release@v1
        with:
          repository: rhysd/actionlint
      - name: Pre-commit
        uses: open-turo/action-pre-commit@v1
